### ISSUE TITLE
`globalMiddleware` can't provide dependencies to authentication middleware

### ISSUE THREAD

**Issue by seveibar** [seamapi/edgespec#56] opened 2024-02-04 19:00 UTC
![image](https://github.com/seamapi/edgespec/assets/1910070/b0a88976-79be-4692-9aca-a42eec220a73)

![image](https://github.com/seamapi/edgespec/assets/1910070/370ce93f-f9d1-40fb-870e-58efdd25fb3d)

![image](https://github.com/seamapi/edgespec/assets/1910070/74826a9c-4c99-4742-b1d5-583b4065d252)

**Comment by codetheweb** [comment] 2024-02-05 19:46
Duplicate of https://github.com/seamapi/edgespec/issues/52.

**Closed as not planned by codetheweb** 2024-02-05 19:46 UTC
